BOTID = '${DISCORD_BOT_ID}'
SERVER = '${DISCORD_SERVER_ID}'
TOKEN = '${DISCORD_BOT_TOKEN}'

ADMIN1 = '${ADMIN1_ID}'
ADMIN2 = '${ADMIN2_ID}'
ADMIN3 = '${ADMIN3_ID}'

SOLOCHANNEL = '${SOLOCHANNEL_ID}'
DUOCHANNEL = '${DUOCHANNEL_ID}'
TRIOCHANNEL = '${TRIOCHANNEL_ID}'
SQUADCHANNEL = '${SQUADCHANNEL_ID}'

SOLOROLE = '${SOLOROLE_ID}'
DUOROLE = '${DUOROLE_ID}'
TRIOROLE = '${TRIOROLE_ID}'
SQUADROLE = '${SQUADROLE_ID}'

SOLO_PAY = True
DUO_PAY = True
TRIO_PAY = True
SQUAD_PAY = True

SOLO_PAY_URL = 'https://sobe.ru/na/' + '${SOLO_PAY_URL}'
DUO_PAY_URL = 'https://sobe.ru/na/' + '${DUO_PAY_URL}'
TRIO_PAY_URL = 'https://sobe.ru/na/' + '${TRIO_PAY_URL}'
SQUAD_PAY_URL = 'https://sobe.ru/na/' + '${SQUAD_PAY_URL}'

YOOMONEY_TOKEN = '${YOOMONEY_TOKEN}'
